#!/bin/bash

case "$1" in
    configure)

        gtk-update-icon-cache
        update-icon-caches /usr/share/icons
        update-desktop-database /usr/share/applications
        
        chmod 777 /opt/hog-1.0/* -R
        chmod 777 /opt/hog-1.0

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
